---
title: "enrollment"
author: "Bria Long"
date: "2024-03-29"
output: html_document
---

# Setup
```{r}
library(tidyverse)
library(here)
```


```{r}
# library(googlesheets4)
# families <- read_sheet('https://docs.google.com/file/d/1EbozDZBPTlaV6Sv9Eeho0CkcVhH6JvsT/edit?filetype=msexcel')
```



```{r}


families = read_csv(file=here::here('data/BabyView Demographic Sheet.csv')) %>%
  select(sid, date_test, date_birth)
```
Load family demographics, IDENTIFIABLE (!)
```{r}
# families = read_csv(here::here('data/release_1.0/babyview_main_demographics.csv')) %>%
  # as_tibble() %>%

# to_join_families <- families %>%
    # rename(sub_id = `Subject ID`) %>%
    # select(sub_id, DoB)  %>%
    # mutate(sub_id = paste0('00',sub_id))
```

Age/video/session_id for main/childz 
```{r}

```

Age/video/session_id for bing kids (not in sampling  or below)
```{r include=FALSE}
# bing_session_demographics <- read_csv(here::here('data/release_1.0/babyview_bing_session_demographics.csv')) %>%
#   mutate(sub_id = pid) %>%
#   mutate(age_during_video = age*12) %>%
#   mutate(video_id = str_split_fixed(file,'_',4)[,2]) %>%
#   select(sub_id, video_id, age_during_video) %>%
#   mutate(cohort='BabyView_Bing')
```

Not using right now
```{r include=FALSE}
# matched_videos_to_join <- read_csv(here::here('traching_sheet_matching_tmp/date_time_tracking_sheet.csv')) %>%
#   rename(sub_id = subject_id) %>%
#   select(sub_id, Date, Processed_Drive_Path, Original_Drive_Path) %>% 
#   left_join(to_join_families) %>%
#   mutate(age_during_video = difftime(mdy(Date), mdy(DoB), units='days')) %>%
#   mutate(age_during_video = as.numeric(age_during_video)/30.1) %>%
#   rename(filename = Processed_Drive_Path) %>%
#   mutate(cohort='BabyView_Main')
```

Not using right now but do need to correct childz dates
```{r include=FALSE}
childz_videos =   read_csv(here::here('data/release_1.0/babyview_childz_sessions.csv')) %>%
  rename(sub_id = subject_id) %>%
  mutate(video_id_new = str_split_fixed(video_id, "H",2)[,2]) %>%
  mutate(video_id_new = paste0('H',video_id_new)) %>%
  select(-video_id) %>%
  rename(video_id = video_id_new) %>%
  select(sub_id, video_id, Date,Time) %>%
  left_join(to_join_families) %>%
  mutate(age_during_video = difftime(mdy(Date), mdy(DoB), units='days')) %>%
  mutate(age_during_video = as.numeric(age_during_video)/30.1) %>%
  mutate(cohort='Ego-SingleChild') %>%
  select(sub_id, video_id, Date, DoB, age_during_video,cohort)
```


# Load duration data

Video durations for main and bing data
```{r}
video_duration = read_csv(here::here('duration/video_durations_with_dates.csv')) %>%
  mutate(filename = str_split_fixed(full_paths,'/',6)[,6]) %>%
  mutate(cohort = 'BV-Main')  %>%
  mutate(sub_id = str_split_fixed(full_paths,'/',6)[,5])  %>%
  mutate(duration_in_minutes = duration/60)
  # left_join(to_join_families) %>%
  # mutate(age_during_video = difftime(ymd(date), mdy(DoB), units='days')) %>%
  # mutate(age_during_video = as.numeric(age_during_video)/30.1) 
```

```{r}
video_duration = read_csv(here::here('duration/video_durations_with_dates.csv')) %>%
  mutate(filename = str_split_fixed(full_paths,'/',6)[,6]) %>%
  mutate(cohort = 'BV-Main')  %>%
  mutate(sub_id = str_split_fixed(full_paths,'/',6)[,5])  %>%
  mutate(duration_in_minutes = duration/60) %>%
  left_join(to_join_families) %>%
  mutate(age_during_video = difftime(ymd(date), mdy(DoB), units='days')) %>%
  mutate(age_during_video = as.numeric(age_during_video)/30.1) 
```

```{r include=FALSE}
video_duration_bing = read_csv(here::here('duration/video_durations_bing.csv')) %>%
  mutate(filename = str_split_fixed(`File Path`,'/',4)[,4]) %>%
  mutate(cohort = 'BV-Preschool')  %>%
  mutate(sub_id = str_split_fixed(`File Path`,'/',4)[,3])  %>%
  mutate(duration_in_minutes = Duration/60) %>% 
  mutate(date = mdy(str_split_fixed(filename,'_',4)[,3])) %>%
  mutate(spring = difftime(date, ymd('2024-03-31'))>0) %>%
  mutate(spring = replace_na(spring,FALSE)) %>%
  filter(!sub_id %in% c('Bobby_Temp')) %>%
  filter(spring==FALSE)
```

# Wrangle data for plot
Look at number of hours by each subject
```{r}
sub_by_duration <- video_duration %>% 
  group_by(sub_id) %>%
  summarize(num_hours = sum(duration_in_minutes)/60)
```


```{r}
main_plot_temp <- video_duration %>%
  filter(!is.na(age_during_video)) %>%
  filter(age_during_video<50) %>% # filtering out videos where things went wrong? FIXME after new data
  filter(age_during_video>0) %>%
  mutate(age_bin = floor(age_during_video)) 

main_plot_age_bin <- main_plot_temp %>%
  group_by(sub_id, age_bin) %>%
  mutate(minutes_recorded = sum(duration_in_minutes)) %>%
  group_by(sub_id) %>%
  arrange(age_bin) %>%
  mutate(minutes_cumulative = cumsum(duration_in_minutes))
```

```{r}
main_plot_ages_all <- main_plot_temp %>%
  filter(!is.na(duration_in_minutes)) %>%
  group_by(sub_id) %>%
  arrange(age_during_video) %>%
  mutate(minutes_cumulative = cumsum(duration_in_minutes)) %>%
  mutate(hours_cumulative = minutes_cumulative/60)
  
```

```{r}
check <- main_plot_temp %>%
  filter(!is.na(duration_in_minutes)) %>%
  group_by(sub_id) %>%
  summarize(hours = sum(duration_in_minutes)/60)

sum(check$hours) # 431 hours, makes sense
```

# Main plot of age by duratino
```{r}
ggplot(main_plot_ages_all, aes(x=age_during_video, y=hours_cumulative, col=sub_id)) +
  geom_point(alpha=.6, size=.5) +
  theme(legend.position='right') +
  ylab('Cumulative hours of videos') +
  xlab('Age (in months) during recording')  +
  theme(legend.position = 'none')

ggsave('age_by_duration.pdf', width=4, units='in')
```

